### ISSUE TITLE
Unable to recognize "e" as a subject.

### ISSUE THREAD

**Issue by khaeghar** [albertogoffi/toradocu#105]
At PrecisionRecallCommonsMath3#testArithmeticUtils, given the comment:

Empty @throws condition. Comment: if e < 0.

The expected is "args[1]<0"

But received empty condition instead.

-> INEQUALITY_0/JJ (root)
  -> e/SYM (dep)
  -> is/VBZ (cop)
  -> ./. (punct)

This is the semantic graph. As you can see, e is a dep for the Stanford Parser, not a noun, therefore, there's no subject we can match.

**Comment by ariannab** [comment]
I'm about to submit the pull request in which we manually POS-tag the code elements as nouns. It should fix this.

**Comment by albertogoffi** [comment]
I agree with Arianna, the algorithm for the custom POStag should be able to cope with these cases.

**Comment by ariannab** [comment]
I think that this should be closed now.

**Comment by albertogoffi** [comment]
We added a custom POS tagging phase to Toradocu that fixes this issue.
