### ISSUE TITLE
Correct translation of arithmetic expressions made with symbols

### ISSUE THREAD

**Issue by khaeghar** [albertogoffi/toradocu#13]
# Correct translation of arithmetic expressions made with symbols

## What was the expected outcome

For the giving throws tag,
```java
@throws IllegalArgumentException if b>1
```

The outcome should be: "condition": "args[0]>1"

## What happened instead?

The outcome of the program is "condition": " "

It happens always. Even if we change the spaces between the number, the variable and the comparator or the length of the variable.

## Recreate the problem

Create a class with the @throws tag with the following characteristics:

@param {varname}
@throws {Exception} if {varname} {arithmetic comparator} {number}

Then, create the method as specified in the javadoc.

Example:
```java
/**
     *
     * @param b
     * @throws IllegalArgumentException if b<1
      */   
    public int testMethod1  (int b) throws IllegalArgumentException{       
        if(b<1) throw new IllegalArgumentException();
               return b;
    }
```

##  System details

I'm using the devel branch of the project with the .jar that gradlew shadowJar produces.

Those are the .java, the output in .json and the log of the console whne I execute Toradocu
[Files.tar.gz](https://github.com/albertogoffi/toradocu/files/471629/Files.tar.gz)

**Comment by albertogoffi** [comment]
Thank you, Sergio (@khaeghar).

I confirm the bug. Toradocu is not able to identify any proposition in comments that do not contain verbs (e.g., `foo < 1`).

We need to create an ad-hoc solution for this kind of comments (that are not sentences, but rather Java boolean conditions).

**Comment by jammua** [comment]
This bug should be closed as it has been fixed now.

**Comment by albertogoffi** [comment]
I confirm that bug is no longer present in Toradocu (commit d5ca55e56e88484ee32708c15f6975e929ca4a71).
