### ISSUE TITLE
Plural of negative/positive

### ISSUE THREAD

**Issue by khaeghar** [albertogoffi/toradocu#14]
## What was the expected outcome

For the giving throws tag,

@throws IllegalArgumentException if myvar and myvar2 are negative/positive/true/false/null

The outcome should be: 

 "comment": "if myvar and myvar2 are negative",
 "condition": "args[0]<0 && args[1]<0"

"comment": "if myvar and myvar2 are positive",
"condition": "args[0]>0 && args[1]>0"

"comment": "if myvar and myvar2 is negative",
"condition": ""

"comment": "if myvar and myvar2 is positive",
"condition": ""

"comment": "if myvar and myvar2 is true",
"condition": ""

"comment": "if myvar and myvar2 is false",
"condition": ""

"comment": "if myvar and myvar2 is null",
"condition": ""

## What happened instead?

"comment": "if myvar and myvar2 are negative",
        "condition": ""

"comment": "if myvar and myvar2 are positive",
        "condition": ""

 "comment": "if myvar and myvar2 is negative",
        "condition": "args[0]<0 && args[1]<0"

"comment": "if myvar and myvar2 is positive",
        "condition": "args[0]>0 && args[1]>0"

"comment": "if myvar and myvar2 is true",
        "condition": "args[0]==true && args[1]==true"

"comment": "if myvar and myvar2 is false",
        "condition": "args[0]==false && args[1]==false"

 "comment": "if myvar and myvar2 is null",
        "condition": "args[0]==null && args[1]==null"

The type of the variables in the true/false cases, is boolean, in the null case, is Integer, and in the positive/negative, just int.

I'm not a native, so, maybe my English is not good enough to identify if those cases are right or wrong. But I think that, if I'm correct, the program is not able to differentiate between the singular and the plural in a sentence.

But it's kind of confusing, because with the null case, Toradocu creates both conditions, with plural and singular.

## System details

I'm using the devel branch, recently pulled and rebuilt.

**Comment by albertogoffi** [comment]
Fixed with pull request #15. We introduced a more general algorithm for the textual pattern matching.
