### ISSUE TITLE
Unable to process conjunction of conditions

### ISSUE THREAD

**Issue by khaeghar** [albertogoffi/toradocu#18]
# Unable to procces conjunction of conditions

## What was the expected outcome

For the giving throws tag,

@throws IllegalArgumentException if myvar1 is less than 1 and myvar2 is less than 3

The outcome should be: "condition": "args[0] <1 && args[1]<3"

## What happened instead?

Toradocu wasn't able to create the condition properly

Actual condition: "args[0]<1"

AJ already identified where's the problem:

>  Text: "if myvar1 is less than 0 and myvar2 is less than 3"
>     Expected: "myvar1<0 && myvar2<3"
>     Actual: "myvar1<0"
>     The original text gets preprocessed to "if myvar1 is INEQUALITY_0 and myvar2 is INEQUALITY_1".
>     The problem is with the semantic graph.
>     
>     Semantic graph:
>     -> INEQUALITY_0/NN (root)
>       -> countMap/NN (nsubj)
>       -> is/VBZ (cop)
>       -> and/CC (cc)
>       -> size/NN (conj:and)
>       -> INEQUALITY_1/JJ (acl:relcl)
>         -> is/VBZ (cop)
> 
>     Only "myvar1" has a subject relation. As a result, the SentenceParser does not attempt to create a proposition with "myvar2" as the subject.

## Recreate the problem:

Create a class with the @throws tag with two conditions joined by a conjunction

## System details
I'm using the devel branch of the project with the .jar that gradlew shadowJar produces.

**Comment by albertogoffi** [comment]
Closed by d7c4be2a9829f82ebd60695c7cc96fbe282761c9.
