### ISSUE TITLE
Feature request: instanceof

### ISSUE THREAD

**Issue by khaeghar** [albertogoffi/toradocu#20]
# Feature request: instanceof

I want to add the feature of the comparator `instanceof` into the rest of the comparators.

An example of its behavior can be something like this:

With the throws tag:
" `@throws IllegalArgumentException if myvar is not an instance of BinaryMutation` "

the output for the condition of Toradocu could be like this:

`condition: "args[0] instanceof BinaryMutation"`

**Comment by albertogoffi** [comment]
Closed by commit e54f01b07858b6c9bce169638f753d9f8541d8e1.
