### ISSUE TITLE
class "ExecutableMember" can't be find

### ISSUE THREAD

**Issue by meikerwang** [albertogoffi/toradocu#242]
in file ./src/main/java/org/toradocu/util/old/GoalFileConverter.java [file](https://github.com/albertogoffi/toradocu/blob/master/src/main/java/org/toradocu/util/old/GoalFileConverter.java),line 19 , there are maybe an error???

When I use this class of [v3.0 project](https://github.com/albertogoffi/toradocu/archive/v3.0.zip), the class "org.toradocu.extractor.ExecutableMember" can't be import successfully

And in package org.toradocu.extractor, there is no class called ExecutableMember.

How can I solve this problem?

**Comment by mernst** [comment]
I'm sorry you are having trouble.
Can you tell us what command you ran that caused an error, and exactly what the error was?
I downloaded and unpacked the 3.0 release, and ran `./gradlew assemble` within it.

**Comment by meikerwang** [comment]
in **master** branch or v3.0 release, the class **"org.toradocu.extractor.ExecutableMember"** can't be found when I tried to read the source code to know how the project worked.


in file "**./src/main/java/org/toradocu/util/old/SpecsChecker.java**" 
 line 12: `import org.toradocu.extractor.ExecutableMember;`

```java
package org.toradocu.util.old;

import static java.util.stream.Collectors.toList;

import com.google.gson.reflect.TypeToken;
import java.io.BufferedReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.toradocu.extractor.ExecutableMember;
import org.toradocu.extractor.ParamTag;
import org.toradocu.extractor.ThrowsTag;
import org.toradocu.util.GsonInstance;

public class SpecsChecker {

  public static void main(String[] args) throws Exception {
    if (args.length != 1) {
      System.out.println("This program must be invoked with the following parameter:");
      System.out.println("1) Path to the JSON specs file to be checked.");
      System.exit(1);
    }

    // Path to the JSON goal file to convert.
    final String inputFilePath = args[0];

    java.lang.reflect.Type listType = new TypeToken<List<ExecutableMember>>() {}.getType();
    try (BufferedReader reader = Files.newBufferedReader(Paths.get(inputFilePath))) {
      System.out.println("Checking specs from " + inputFilePath);
      List<ExecutableMember> methods = GsonInstance.gson().fromJson(reader, listType);
      checkThrowsConsistency(methods);
      checkParamThrowsConsistency(methods);
    }
  }
```


I compiled the project successfully, but I just was confused about there was no class named "**ExecutableMember**" in the **package** "org.toradocu.extractor"

**Comment by mernst** [comment]
The `old/` directory contains old, out-of-date code.
It is [excluded](https://github.com/albertogoffi/toradocu/blob/master/build.gradle#L72) from compilation and tests, so you should not read it while trying to understand Toradocu.
