### ISSUE TITLE
Wrong translation of comments involving instanceof

### ISSUE THREAD

**Issue by albertogoffi** [albertogoffi/toradocu#46]
Of the method `org.apache.commons.math3.genetics.CycleCrossover.crossover(Chromosome first, Chromosome second)`, the comment `if the chromosomes are not an instance of AbstractListChromosome` is translated as `(args[0] instanceof AbstractListChromosome) == false`. Instead, the expected output is `(args[0] instanceof AbstractListChromosome) == false || (args[1] instanceof AbstractListChromosome) == false`.

**Comment by khaeghar** [comment]
This issue is also on issue #26 I think, isn't it?

**Comment by albertogoffi** [comment]
Thanks @khaeghar, is actually the same bug. Thanks for having noticed that.
