### ISSUE TITLE
Creating conditions for inaccessible classes, methods and/or parameter types

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#54]
Running Toradocu on `org.apache.commons.collections4.bidimap.TreeBidiMap` with `--export-conditions` (on `randoop` branch) get

```java
    // void org.apache.commons.collections4.bidimap.TreeBidiMap.checkNonNullComparable(java.lang.Object o,org.apache.commons.collections4.bidimap.TreeBidiMap.DataElement dataElement)
    public static boolean m51_t0(org.apache.commons.collections4.bidimap.TreeBidiMap target, java.lang.Object o, org.apache.commons.collections4.bidimap.TreeBidiMap.DataElement dataElement) {
        // @throws java.lang.NullPointerException if o is null ==> args[0]==null
        return o == null;
    }
```

where `checkNonNullComparable()` is a `private` method of the class. 

Though, the condition class doesn't compile because `org.apache.commons.collections4.bidimap.TreeBidiMap.DataElement` is package private.

**Comment by bjkeller** [comment]
A similar problem affects 14 classes in Commons Collections that have to be excluded from Toradocu-Randoop evaluation.

**Comment by bjkeller** [comment]
Also, not excluding private classes such as `org.apache.commons.collections4.trie.AbstractPatriciaTrie`

**Comment by albertogoffi** [comment]
A possible (partial?) solution could be place the condition class in the a package with the same name of the target class' package. What do you think?

**Comment by bjkeller** [comment]
I think that makes sense.  

In general, the goal is that the condition classes compile, so whatever makes that possible. This won't be directly possible when the condition method has parameter types that are private. So, when the target class is private, as in
```java
private class CannotBeUsedDirectly { 
  void subjectMethod(int val) { ... }
}
```
or when one of the parameter types is a private member of the target class
```java
public class CanBeUsed {
  void subjectMethod(PrivateMember arg) { ... }
  private class PrivateMember {...}
}
```

My guess is that you can lift these to a public supertype in the condition method (keeping the correct types in the JSON). There may be conditions that cannot be expressed properly, but, regardless, I think you should be prepared to drop some conditions because they cannot be made public.

**Comment by albertogoffi** [comment]
Now Toradocu generates condition-checking methods only for non-private methods.
Also, the condition-checking class has now the appropriate package definition (the package is the same as the target class).

Do we need additional checks for the parameter types of the condition-checking methods? 
In that case, can you provide me few example where the compilation of the condition-checking class fails because of the private type of the parameters?

**Comment by bjkeller** [comment]
I think this change should be sufficient, as i don't think it should be possible to compile the subject class with a parameter type with more restrictive access than the method.

**Comment by bjkeller** [comment]
If condition class is going into the package for the target class, Toradocu also needs to manage the directory structure.  For example, for the tutorial, if command is
```
java -jar ../build/libs/toradocu-1.0-all.jar --target-class net.Connection --source-dir src/net --class-dir src/net --condition-translator-output conditions/net_Connection.json --oracle-generation false --export-conditions conditions
```
the file tree should be 
```
conditions
├── net
│   └── net_Connection.java
└── net_Connection.json
```

**Comment by bjkeller** [comment]
Also, it turns out that there is not enough information in `org.toradocu.extractor.Type` to determine the package name of a member class (assuming issue  is fixed).

**Comment by bjkeller** [comment]
The original issues is resolved for Apache Commons Collections, but still need to fix directory structure.

**Comment by bjkeller** [comment]
I'm going to close this because the original issue is resolved.
