### ISSUE TITLE
Vacuous self-referential conditions are generated

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#98]
The following  Randoop specification is being generated by Toradocu
```
  {
    "operation": {
      "classname": "org.apache.commons.collections4.BoundedMap",
      "name": "isFull",
      "parameterTypes": []
    },
    "identifiers": {
      "parameters": [],
      "receiverName": "target",
      "returnName": "result"
    },
    "throwsSpecifications": [],
    "postSpecifications": [
      {
        "property": {
          "conditionText": "result==true",
          "description": "true if the map is full"
        },
        "description": "return true if the map is full",
        "guard": {
          "conditionText": "target.isFull()",
          "description": ""
        }
      }
    ],
    "preSpecifications": []
  }
```
This is the condition "if target.isFull() then target.isFull()". I don't expect this to cause problems for Randoop, but it certainly isn't very interesting.

**Comment by mernst** [comment]
This seems nonsensical to me.  I could see it leading to an infinite loop in Randoop or other tools.

**Comment by bjkeller** [comment]
It would only be a problem if the guard were being injected into the method, which we are not doing in Randoop.

**Comment by albertogoffi** [comment]
Thank you for the report. 

Toradocu should not generate specifications for a method that mention the method itself.
I'm going to investigate why this is happening.
