### ISSUE TITLE
Toradocu not using Class.getName() format for names of member class types in Randoop specifications

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#99]
Toradocu is generating Randoop specifications that don't use `Class.forName()` format for member class types when describing methods/constructors.

In particular, the parameter type of the method `org.apache.commons.collections4.comparators.FixedOrderComparator.setUnknownObjectBehavior(org.apache.commons.collections4.comparators.FixedOrderComparator.UnknownObjectBehavior)`
is given incorrectly as
`org.apache.commons.collections4.comparators.FixedOrderComparator.UnknownObjectBehavior`.
and instead needs to be 
`org.apache.commons.collections4.comparators.FixedOrderComparator$UnknownObjectBehavior`.

There is code that translates the declaring class of a method, but the parameter types are not modified.

**Comment by albertogoffi** [comment]
The method responsible of the generation of the parameter types is `randoop.condition.specification.Operation#getTypeNames`. The method uses canonical name instead of the name for the parameter types.

**Comment by bjkeller** [comment]
My apology, I didn't see that you had made the conversion to use reflection types.

Thanks for that fix.
